# synced from the private monorepo at release time — do not edit here
param(
    [Parameter(Mandatory)][string]$Central,
    [Parameter(Mandatory)][string]$Token,
    [string]$Org = "default",
    [string]$Node = $env:COMPUTERNAME,
    [string]$RepoUrl = "https://github.com/haneeshbyreddy/ping_tool.git",
    [string]$Branch = "main"
)

$ErrorActionPreference = 'Stop'

function Log { param([string]$m) Write-Host "> $m" -ForegroundColor Cyan }
function Ok  { param([string]$m) Write-Host "OK $m" -ForegroundColor Green }
function Die { param([string]$m) Write-Host "X  $m" -ForegroundColor Red; exit 1 }

$InstallDir = "C:\WISP"
$RepoDir    = Join-Path $InstallDir "src-repo"
$ConfigDir  = Join-Path $env:ProgramData "WISP"
$TaskName   = "WISP-Edge-Source"

function Ensure-Tool {
    param([string]$Cmd, [string]$WingetId, [string]$FriendlyName)
    if (Get-Command $Cmd -ErrorAction SilentlyContinue) { return }
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        Log "$FriendlyName not found — installing via winget..."
        winget install --id $WingetId -e --silent --accept-package-agreements --accept-source-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + `
                    [System.Environment]::GetEnvironmentVariable("Path","User")
    }
    if (-not (Get-Command $Cmd -ErrorAction SilentlyContinue)) {
        Die "$FriendlyName still not on PATH — install it manually, then re-run this script."
    }
    Ok "$FriendlyName installed"
}

Ensure-Tool -Cmd git -WingetId "Git.Git" -FriendlyName "Git"

function Resolve-Python {
    $found = @()
    $found += Get-ChildItem 'C:\Program Files\Python3*\python.exe','C:\Python3*\python.exe' `
                 -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName
    Get-Command python.exe -All -ErrorAction SilentlyContinue | ForEach-Object {
        if ($_.Source -and $_.Source -notmatch 'WindowsApps') { $found += $_.Source }
    }
    foreach ($p in ($found | Select-Object -Unique)) {
        if (Test-Path $p) {
            & $p -c "import sys" 2>$null
            if ($LASTEXITCODE -eq 0) { return $p }
        }
    }
    return $null
}

$Python = Resolve-Python
if (-not $Python) {
    if (Get-Command winget -ErrorAction SilentlyContinue) {
        Log "no all-users Python found (Store Python can't run as SYSTEM) — installing python.org build for all users..."
        winget install --id Python.Python.3.13 -e --scope machine --silent `
            --accept-package-agreements --accept-source-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + `
                    [System.Environment]::GetEnvironmentVariable("Path","User")
        $Python = Resolve-Python
    }
}
if (-not $Python) {
    Die ("No usable all-users Python. The Microsoft Store build won't work for a SYSTEM " +
         "service. Install Python from https://python.org with 'Install for all users' " +
         "checked, turn off the Store 'python.exe' app-execution alias, then re-run this script.")
}
Ok "using Python at $Python"

New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null

if (Test-Path (Join-Path $RepoDir ".git")) {
    Log "repo exists, pulling latest $Branch..."
    Push-Location $RepoDir
    git fetch origin $Branch
    git reset --hard "origin/$Branch"
    Pop-Location
} else {
    Log "cloning $RepoUrl ($Branch)..."
    git clone --branch $Branch --depth 1 $RepoUrl $RepoDir
}
Ok "source at $RepoDir"

Log "setting up venv + installing deps (icmplib/httpx/pysnmp)..."
if (Test-Path (Join-Path $RepoDir ".venv")) { Remove-Item (Join-Path $RepoDir ".venv") -Recurse -Force }
& $Python -m venv (Join-Path $RepoDir ".venv")
& (Join-Path $RepoDir ".venv\Scripts\pip.exe") install -q -r (Join-Path $RepoDir "requirements.txt")
Ok "deps installed"

$envFile = Join-Path $ConfigDir "edge.env.ps1"
Log "writing $envFile (identity + central config)..."
@"
# GENERATED by install-edge-src.ps1 — edit values, not structure. A re-run/update
# only touches the source checkout + venv, never this file.
`$env:WISP_CENTRAL_URL = '$Central'
`$env:WISP_CENTRAL_TOKEN = '$Token'
`$env:WISP_ORG_ID = '$Org'
`$env:WISP_NODE_ID = '$Node'
"@ | Set-Content -Path $envFile -Encoding ASCII
Ok "wrote identity/config"

$launcher = Join-Path $ConfigDir "run-edge.cmd"
@"
@echo off
rem GENERATED by install-edge-src.ps1 — runs the agent directly from source (dev/quick
rem install path, not the signed fleet binary). Edit %ProgramData%\WISP\edge.env.ps1
rem for connection settings; re-run install-edge-src.ps1 to pull source updates.
powershell -NoProfile -ExecutionPolicy Bypass -Command ". '$envFile'; & '$RepoDir\.venv\Scripts\python.exe' '$RepoDir\apps\daemon\main.py'"
"@ | Set-Content -Path $launcher -Encoding ASCII

Log "registering scheduled task (runs as SYSTEM, starts at boot, restarts on crash)..."
$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$trigger   = New-ScheduledTaskTrigger -AtStartup
$settings  = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -MultipleInstances IgnoreNew `
    -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero)

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}
$action = New-ScheduledTaskAction -Execute $launcher -WorkingDirectory $RepoDir
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Description 'WISP edge (source path, quick install)' -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName

Write-Host ''
Ok "WISP edge (source path) installed and started. Node $Org/$Node -> $Central."
Write-Host "  status: Get-ScheduledTask $TaskName | Get-ScheduledTaskInfo"
Write-Host "  logs:   run '$launcher' by hand in a console to see live output"
Write-Host "  stop:   Stop-ScheduledTask -TaskName $TaskName"
