#!/usr/bin/env bash
# synced from the private monorepo at release time — do not edit here
set -euo pipefail

CENTRAL="" TOKEN="" ORG="default" NODE="$(hostname)"
REPO_URL="https://github.com/haneeshbyreddy/ping_tool.git"
BRANCH="main"
PREFIX=/opt/wisp
CONFIG_DIR=/etc/wisp

log() { echo "> $*"; }
err() { echo "X $*" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --central) CENTRAL="$2"; shift 2;;
    --token)   TOKEN="$2"; shift 2;;
    --org)  ORG="$2"; shift 2;;
    --node)    NODE="$2"; shift 2;;
    --repo-url) REPO_URL="$2"; shift 2;;
    --branch)  BRANCH="$2"; shift 2;;
    *) err "unknown arg: $1";;
  esac
done
[ "$(id -u)" -eq 0 ] || err "run as root (use sudo)"
[ -n "$CENTRAL" ] || err "--central is required"
[ -n "$TOKEN" ] || err "--token is required"

command -v git >/dev/null 2>&1 || err "git not found — install it first (apt/yum/etc.)"
command -v python3 >/dev/null 2>&1 || err "python3 not found — install it first"

REPO_DIR="$PREFIX/src-repo"
mkdir -p "$PREFIX" "$CONFIG_DIR"

if [ -d "$REPO_DIR/.git" ]; then
  log "repo exists, pulling latest $BRANCH..."
  git -C "$REPO_DIR" fetch origin "$BRANCH"
  git -C "$REPO_DIR" reset --hard "origin/$BRANCH"
else
  log "cloning $REPO_URL ($BRANCH)..."
  git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$REPO_DIR"
fi
log "source at $REPO_DIR"

log "setting up venv + installing deps (icmplib/httpx/pysnmp)..."
python3 -m venv "$REPO_DIR/.venv"
"$REPO_DIR/.venv/bin/pip" install -q -r "$REPO_DIR/requirements.txt"
log "deps installed"

sysctl -w net.ipv4.ping_group_range="0 2147483647" >/dev/null
if ! grep -q '^net.ipv4.ping_group_range' /etc/sysctl.conf 2>/dev/null; then
  echo 'net.ipv4.ping_group_range = 0 2147483647' >> /etc/sysctl.conf
fi

ENV_FILE="$CONFIG_DIR/edge.env"
log "writing $ENV_FILE (identity + central config)..."
cat > "$ENV_FILE" <<EOF
# GENERATED by install-edge-src.sh — edit values, not structure. A re-run/update
# only touches the source checkout + venv, never this file.
WISP_CENTRAL_URL=$CENTRAL
WISP_CENTRAL_TOKEN=$TOKEN
WISP_ORG_ID=$ORG
WISP_NODE_ID=$NODE
EOF
chmod 600 "$ENV_FILE"
log "wrote identity/config"

SERVICE_FILE=/etc/systemd/system/wisp-edge-src.service
log "writing $SERVICE_FILE..."
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=WISP Edge (source path, quick install)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$REPO_DIR
ExecStart=$REPO_DIR/.venv/bin/python3 apps/daemon/main.py
EnvironmentFile=$ENV_FILE
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now wisp-edge-src

echo ""
log "WISP edge (source path) installed and started. Node $ORG/$NODE -> $CENTRAL."
echo "  status: systemctl status wisp-edge-src"
echo "  logs:   journalctl -u wisp-edge-src -f"
echo "  stop:   systemctl stop wisp-edge-src"
